apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    steps:
      - name: Deploy App1-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].digest }}
          target-environment: pre-prod
          name: App1-Frontend

      - name: Deploy App1-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].digest }}
          target-environment: pre-prod
          name: App1-Backend

      - name: Deploy App1-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].digest }}
          target-environment: pre-prod
          name: App1-APIs
  prod:
    needs: pre-prod
    steps:
      - name: Deploy App1-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App1-Frontend']['App1-Frontend'].digest }}
          target-environment: prod
          name: App1-Frontend

      - name: Deploy App1-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App1-Backend']['App1-Backend'].digest }}
          target-environment: prod
          name: App1-Backend

      - name: Deploy App1-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App1-APIs']['App1-APIs'].digest }}
          target-environment: prod
          name: App1-APIs
